// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    $("#color1").html("...");
    $("#color2").html("titty bfast");
    $("#color3").html("everyday");
    $("#color4").html("for");
    $("#color5").html("a");
    return $("#color6").html("strong body");
  });

}).call(this);
