// Generated by CoffeeScript 1.3.1
(function() {
  var c, convert_list_to_rgb, randc, read_variables_from_url;

  $(function() {
    var c_str1, c_str2, c_str3, c_str4, c_str5, c_str6, nums_from_url;
    $("a#titlelink").attr("href", document.URL.split("?")[0] + '?color1=' + c() + '&color2=' + c() + '&color3=' + c() + '&color4=' + c() + '&color5=' + c() + '&color6=' + c());
    nums_from_url = read_variables_from_url();
    c_str1 = convert_list_to_rgb(nums_from_url['color1']);
    $("#color1").css("background-color", c_str1);
    $("#color1").click(function() {
      return $(this).html(c_str1);
    });
    nums_from_url = read_variables_from_url();
    c_str2 = convert_list_to_rgb(nums_from_url['color2']);
    $("#color2").css("background-color", c_str2);
    $("#color2").click(function() {
      return $(this).html(c_str2);
    });
    nums_from_url = read_variables_from_url();
    c_str3 = convert_list_to_rgb(nums_from_url['color3']);
    $("#color3").css("background-color", c_str3);
    $("#color3").click(function() {
      return $(this).html(c_str3);
    });
    nums_from_url = read_variables_from_url();
    c_str4 = convert_list_to_rgb(nums_from_url['color4']);
    $("#color4").css("background-color", c_str4);
    $("#color4").click(function() {
      return $(this).html(c_str4);
    });
    nums_from_url = read_variables_from_url();
    c_str5 = convert_list_to_rgb(nums_from_url['color5']);
    $("#color5").css("background-color", c_str5);
    $("#color5").click(function() {
      return $(this).html(c_str5);
    });
    nums_from_url = read_variables_from_url();
    c_str6 = convert_list_to_rgb(nums_from_url['color6']);
    $("#color6").css("background-color", c_str6);
    return $("#color6").click(function() {
      return $(this).html(c_str6);
    });
  });

  randc = function() {
    return Math.round(Math.random() * 256);
  };

  c = function() {
    return [randc(), randc(), randc()];
  };

  convert_list_to_rgb = function(rgb_list) {
    return 'rgb(' + rgb_list[0] + "," + rgb_list[1] + "," + rgb_list[2] + ')';
  };

  read_variables_from_url = function() {
    var entry, hash, q, vars, _i, _len;
    vars = {};
    q = document.URL.split("?")[1];
    if (q) {
      q = q.split("&");
      for (_i = 0, _len = q.length; _i < _len; _i++) {
        entry = q[_i];
        hash = entry.split("=");
        vars[hash[0]] = hash[1].split(',');
      }
      return vars;
    } else {
      return location.assign('?color1=' + c() + '&color2=' + c() + '&color3=' + c() + '&color4=' + c() + '&color5=' + c() + '&color6=' + c());
    }
  };

}).call(this);
